services:
  mysql:
    image: mysql:8.0
    container_name: mysql-test
    environment:
      - MYSQL_ROOT_PASSWORD=testpw
      - MYSQL_DATABASE=testdb
    ports:
      - "3308:3306"

  redis:
    image: redis:latest
    container_name: redis-test
    ports:
      - "6380:6379"
