spring:
  application:
    name: yoajung-server

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true

    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      database: 0
      timeout: 2000ms

  session:
    timeout: 30m
    redis:
      namespace: spring:session

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          timeout: 5000
          write timeout: 5000
  email-code-expiration-millis: 1800000
  password-reset-token-expiration-millis: 600000

  ai:
    openai:
      api-key: "${OPENAI_API_KEY}"
      chat:
        options:
          model: gpt-4o
          temperature: 0.5
    chat:
      system-prompt1: classpath:prompt/prompt1.txt
      system-prompt2: classpath:prompt/prompt2.txt
      system-prompt3: classpath:prompt/prompt3.txt
      system-prompt4: classpath:prompt/prompt4.txt

      memory:
        repository:
          jdbc:
            initialize-schema: never
            platform: mariadb
server:
  servlet:
    session:
      cookie:
        name: JSESSIONID_USER
        http-only: true

#logging:
#  level:
#    org.hibernate.SQL: debug             # 실행되는 SQL 로그
#    org.hibernate.type.descriptor.sql: trace   # 바인딩된 파라미터 값도 출력됨

kakao:
  client-id: ${REST_API_KEY}
  redirect-uri: ${REDIRECT_URI}


